version: '2'
services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CREATE_TOPICS: "itemlocation:1:1"
    depends_on:
      - zookeeper
